package file

import (
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"os"
	"sort"

	"gopkg.in/yaml.v3"
)

const (
	header = "# Generated by apidep. DO NOT EDIT.\n"
)

// ApiLock mirrors the generated api.lock.yml file.
type ApiLock struct {
	Version int       `yaml:"version"`
	Deps    []DepLock `yaml:"deps"`
}

// Upsert replaces the entry for entry.Source, or appends it if absent.
// It returns true if the lock was modified.
func (l *ApiLock) Upsert(entry DepLock) bool {
	for i, d := range l.Deps {
		if d.Source == entry.Source {
			if d == entry {
				return false
			}
			l.Deps[i] = entry
			return true
		}
	}
	l.Deps = append(l.Deps, entry)
	return true
}

// Get returns the lock entry for source, if present.
func (l *ApiLock) Get(source string) (*DepLock, bool) {
	for i := range l.Deps {
		if l.Deps[i].Source == source {
			return &l.Deps[i], true
		}
	}
	return nil, false
}

// DepLock records the resolved commit and content hash of one dependency.
type DepLock struct {
	Source string `yaml:"source"`
	Commit string `yaml:"commit,omitempty"`
	Hash   string `yaml:"hash"`
}

// NewLock returns an empty lock at the current version.
func NewLock() *ApiLock {
	return &ApiLock{Version: version}
}

// ReadLock loads a lock file, returning an empty lock when it doesn't exist.
func ReadLock(filePath string) (*ApiLock, error) {
	data, err := os.ReadFile(filePath)
	if os.IsNotExist(err) {
		return NewLock(), nil
	}
	if err != nil {
		return nil, fmt.Errorf("read lock %s: %w", filePath, err)
	}
	var lock ApiLock
	if err := yaml.Unmarshal(data, &lock); err != nil {
		return nil, fmt.Errorf("parse lock %s: %w", filePath, err)
	}
	return &lock, nil
}

// WriteLock serializes lock to filePath with the generated-file header.
func WriteLock(filePath string, lock *ApiLock) error {
	data, err := serialize(lock)
	if err != nil {
		return fmt.Errorf("serialize lock: %w", err)
	}
	content := append([]byte(header), data...)
	if err := os.WriteFile(filePath, content, filePerm); err != nil {
		return fmt.Errorf("write lock %s: %w", filePath, err)
	}
	return nil
}

// Hash returns a stable content hash over the path-keyed file contents,
// independent of map iteration order.
func Hash(refs map[string][]byte) string {
	paths := make([]string, 0, len(refs))
	for p := range refs {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	hash := sha256.New()
	for _, p := range paths {
		h := sha256.Sum256(refs[p])
		fmt.Fprintf(hash, "%s:%x\n", p, h)
	}
	return prefix(version) + ":" + base64.StdEncoding.EncodeToString(hash.Sum(nil))
}

func prefix(version int) string {
	return fmt.Sprintf("h%d", version)
}
